# Generated by Django 3.2.16 on 2024-04-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee'), ('coordinator', 'Coordinator'), ('supervisor', 'Supervisor')], max_length=11),
        ),
    ]
