# Generated by Django 3.2.16 on 2024-03-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResults',
            fields=[
                ('course_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('course_type', models.CharField(choices=[('1', 'Programming'), ('2', 'Business')], max_length=15)),
                ('score', models.IntegerField()),
                ('programming_average', models.FloatField(blank=True, null=True)),
                ('business_average', models.FloatField(blank=True, null=True)),
                ('reg_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
