# Generated by Django 3.2.16 on 2024-03-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20240320_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseResults',
            new_name='CourseResult',
        ),
    ]
