# Generated by Django 3.2.16 on 2024-03-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_rename_reg_number_courseresult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
