# Generated by Django 3.2.16 on 2024-03-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_auto_20240331_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
    ]
