# Generated by Django 3.2.16 on 2024-03-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_remove_job_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('course_type', models.CharField(choices=[('1', 'Programming'), ('2', 'Business')], max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='courseresult',
            old_name='score',
            new_name='mark',
        ),
        migrations.RemoveField(
            model_name='courseresult',
            name='business_average',
        ),
        migrations.RemoveField(
            model_name='courseresult',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='courseresult',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='courseresult',
            name='programming_average',
        ),
        migrations.AddField(
            model_name='courseresult',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='business_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='programming_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseresult',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.course'),
        ),
    ]
