# Generated by Django 3.2.16 on 2024-03-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_auto_20240331_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
