# Generated by Django 3.2.16 on 2024-03-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_auto_20240331_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_applicants_to_select',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
