# Generated by Django 3.2.16 on 2024-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_job_num_applicants_to_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1', 'Programming'), ('2', 'Business')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
