# Generated by Django 3.2.16 on 2024-04-11 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0015_auto_20240403_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_at_work', models.CharField(max_length=100)),
                ('contact_details_work', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('registration_status', models.BooleanField(default=True)),
                ('supervisor_from_school', models.CharField(max_length=100)),
                ('contact_details_school', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('first_visit_details', models.TextField()),
                ('first_marks', models.IntegerField()),
                ('second_visit_details', models.TextField()),
                ('second_marks', models.IntegerField()),
                ('period_of_attachment', models.CharField(max_length=100)),
                ('change_of_company', models.BooleanField(default=False)),
                ('additional_comments', models.TextField()),
                ('attached_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='job',
        ),
        migrations.RemoveField(
            model_name='match',
            name='reg_number',
        ),
        migrations.AddField(
            model_name='student',
            name='registration_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='attatchment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Communication',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddField(
            model_name='attachmentstudent',
            name='reg_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.student'),
        ),
        migrations.AddField(
            model_name='attachmentstudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
