# Generated by Django 3.2.16 on 2024-04-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_auto_20240411_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(default='https://theriversfamilychat.blogspot.com', max_length=100),
            preserve_default=False,
        ),
    ]
