# Generated by Django 3.2.16 on 2024-04-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_company_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='website',
            new_name='url',
        ),
    ]
