# Generated by Django 3.2.16 on 2024-04-21 13:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_alter_student_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentstudent',
            name='contact_details_school',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='attachmentstudent',
            name='first_visit_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachmentstudent',
            name='second_visit_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachmentstudent',
            name='supervisor_from_school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
