# Generated by Django 3.2.16 on 2024-04-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_auto_20240421_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentstudent',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachmentstudent',
            name='first_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachmentstudent',
            name='period_of_attachment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attachmentstudent',
            name='second_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
