# Generated by Django 3.2.16 on 2024-04-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0025_auto_20240421_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentstudent',
            name='has_school_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
