# Generated by Django 3.2.16 on 2024-04-26 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0028_auto_20240421_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentstudent',
            name='contact_details_school',
        ),
        migrations.RemoveField(
            model_name='attachmentstudent',
            name='contact_details_work',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='schoolsupervisor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='schoolsupervisor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.CreateModel(
            name='WorkSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='attachmentstudent',
            name='supervisor_at_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.worksupervisor'),
        ),
    ]
