# Generated by Django 3.2.16 on 2024-04-26 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0030_company_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksupervisor',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobapp.company'),
            preserve_default=False,
        ),
    ]
