# Generated by Django 3.2.16 on 2024-04-26 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0031_worksupervisor_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentstudent',
            name='first_marks',
        ),
        migrations.RemoveField(
            model_name='attachmentstudent',
            name='first_visit_details',
        ),
        migrations.RemoveField(
            model_name='attachmentstudent',
            name='second_marks',
        ),
        migrations.RemoveField(
            model_name='attachmentstudent',
            name='second_visit_details',
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.IntegerField()),
                ('visit_details', models.TextField()),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.attachmentstudent')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
