# Generated by Django 3.2.16 on 2024-04-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0033_alter_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='visit_details',
            new_name='assessment_details',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='visit_number',
            new_name='assessment_number',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
