# Generated by Django 3.2.16 on 2024-04-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0034_auto_20240428_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentstudent',
            name='additional_comments',
        ),
        migrations.AddField(
            model_name='assessment',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
