# Generated by Django 3.2.16 on 2024-04-28 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0037_alter_assessment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assessment', to=settings.AUTH_USER_MODEL),
        ),
    ]
